_process: not_implemented
aft:
    _process: not_implemented
    address-family:
        _process: not_implemented
    config:
        _process: not_implemented
        address-family:
            _process: not_implemented
    entries:
        _process: not_implemented
        entry:
            _process: not_implemented
            config:
                _process: not_implemented
                index:
                    _process: not_implemented
            index:
                _process: not_implemented
            match:
                _process: not_implemented
                interface-ref:
                    _process: not_implemented
                    state:
                        _process: not_implemented
                state:
                    _process: not_implemented
            next-hops:
                _process: not_implemented
                next-hop:
                    _process: not_implemented
                    config:
                        _process: not_implemented
                        index:
                            _process: not_implemented
                    index:
                        _process: not_implemented
                    interface-ref:
                        _process: not_implemented
                        config:
                            _process: not_implemented
                            interface:
                                _process: not_implemented
                            subinterface:
                                _process: not_implemented
                        state:
                            _process: not_implemented
                    state:
                        _process: not_implemented
            state:
                _process: not_implemented
    state:
        _process: not_implemented

