---
metadata:
    parser: XMLExtractor
    execute:
        config: {}

routed_vlan:
    _parse: not_implemented
    config:
        _parse: not_implemented
        vlan:
            _parse: not_implemented
