---
metadata:
    prefix: "oc-vlan"
    processor: TextTree

vlan:
    _process: unnecessary
    config:
        _process: unnecessary
        vlan-id:
            _process:
                - path: "encapsulation.dot1q.vlan"
