---
metadata:
    prefix: "oc-vlan"
    parser: TextExtractor

routed-vlan:
    _parse: unnecessary
    config:
        _parse: unnecessary
        enabled:
            _parse: unnecessary
        vlan:
            _parse: unnecessary
