---
metadata:
    processor: TextTree
    execute:
        - method: cli
          kwargs:
              commands: ["show running-config all"]
system:
    _process: unnecessary
    aaa:
        _process: unnecessary
        accounting:
            _process: not_implemented
            config:
                _process: not_implemented
                accounting-method:
                    _process: not_implemented
            events:
                _process: not_implemented
                event:
                    _process: not_implemented
                    config:
                        _process: not_implemented
                        event-type:
                            _process: not_implemented
                        record:
                            _process: not_implemented
                    event-type:
                        _process: not_implemented
                    state:
                        _process: not_implemented
            state:
                _process: not_implemented
        authentication:
            _process: unnecessary
            admin-user:
                _process: unnecessary
                config:
                    _process: unnecessary
                    admin-password:
                        _process: not_implemented
                    admin-password-encrypted:
                        _process:
                            - path: "aaa.root.secret"
                              from: root_system.0
                              regexp: "(?P<value>(5|sha512) \\S+)$"
                state:
                    _process: not_implemented
            config:
                _process: not_implemented
                authentication-method:
                    _process: not_implemented
            state:
                _process: not_implemented
            users:
                _process: unnecessary
                user:
                    _process:
                        - path: "username"
                          from: root_system.0
                    config:
                        _process: unnecessary
                        password:
                            _process:
                                - path: "privilege"
                                  regexp: "\\d+ password (?P<value>0 \\S+)"
                        password-encrypted:
                            _process:
                                - path: "privilege"
                                  regexp: "\\d+ secret (?P<value>(5|sha512) \\S+)$"
                        role:
                            _process:
                                - path: "privilege"
                                  regexp: "(?P<value>\\d+) secret \\S+"
                                - path: "privilege"
                                  regexp: "(?P<value>\\d+) password \\S+"

                        ssh-key:
                            _process: not_implemented
                        username:
                            _process: unnecessary
                    state:
                        _process: not_implemented
                    username:
                        _process: not_implemented
        authorization:
            _process: not_implemented
            config:
                _process: not_implemented
                authorization-method:
                    _process: not_implemented
            events:
                _process: not_implemented
                event:
                    _process: not_implemented
                    config:
                        _process: not_implemented
                        event-type:
                            _process: not_implemented
                    event-type:
                        _process: not_implemented
                    state:
                        _process: not_implemented
            state:
                _process: not_implemented
        server-groups:
            _process: not_implemented
            server-group:
                _process: not_implemented
                config:
                    _process: not_implemented
                    name:
                        _process: not_implemented
                    type:
                        _process: not_implemented
                name:
                    _process: not_implemented
                servers:
                    _process: not_implemented
                    server:
                        _process: not_implemented
                        address:
                            _process: not_implemented
                        config:
                            _process: not_implemented
                            address:
                                _process: not_implemented
                            name:
                                _process: not_implemented
                            timeout:
                                _process: not_implemented
                        radius:
                            _process: not_implemented
                            config:
                                _process: not_implemented
                                acct-port:
                                    _process: not_implemented
                                auth-port:
                                    _process: not_implemented
                                retransmit-attempts:
                                    _process: not_implemented
                                secret-key:
                                    _process: not_implemented
                                source-address:
                                    _process: not_implemented
                            state:
                                _process: not_implemented
                        state:
                            _process: not_implemented
                        tacacs:
                            _process: not_implemented
                            config:
                                _process: not_implemented
                                port:
                                    _process: not_implemented
                                secret-key:
                                    _process: not_implemented
                                source-address:
                                    _process: not_implemented
                            state:
                                _process: not_implemented
                state:
                    _process: not_implemented
    clock:
        _process: not_implemented
        config:
            _process: not_implemented
            timezone-name:
                _process: not_implemented
        state:
            _process: not_implemented
    config:
        _process: unnecessary
        domain-name:
            _process: not_implemented
        hostname:
            _process:
                - path: "hostname"
                  from: root_system.0
        login-banner:
            _process: not_implemented
        motd-banner:
            _process: not_implemented
    dns:
        _process: not_implemented
        config:
            _process: not_implemented
            search:
                _process: not_implemented
        host-entries:
            _process: not_implemented
            host-entry:
                _process: not_implemented
                config:
                    _process: not_implemented
                    alias:
                        _process: not_implemented
                    hostname:
                        _process: not_implemented
                    ipv4-address:
                        _process: not_implemented
                    ipv6-address:
                        _process: not_implemented
                hostname:
                    _process: not_implemented
                state:
                    _process: not_implemented
        servers:
            _process: not_implemented
            server:
                _process: not_implemented
                address:
                    _process: not_implemented
                config:
                    _process: not_implemented
                    address:
                        _process: not_implemented
                    port:
                        _process: not_implemented
                state:
                    _process: not_implemented
        state:
            _process: not_implemented
    logging:
        _process: unnecessary
        console:
            _process: not_implemented
            selectors:
                _process: not_implemented
                selector:
                    _process: not_implemented
                    config:
                        _process: not_implemented
                        facility:
                            _process: not_implemented
                        severity:
                            _process: not_implemented
                    facility:
                        _process: not_implemented
                    severity:
                        _process: not_implemented
                    state:
                        _process: not_implemented
        remote-servers:
            _process: unnecessary
            remote-server:
                _process:
                    - path: "logging.host.?host.transport.?proto.port.?port"
                      key: host
                      from: root_system.0
                    - path: "logging"
                      from: root_system.0
                      regexp: "(?P<value>\\d+\\.\\d+\\.\\d+\\.\\d+)"
                config:
                    _process: unnecessary
                    host:
                        _process: unnecessary
                    remote-port:
                        _process:
                            - path: port
                    source-address:
                        _process: not_implemented
                host:
                    _process: not_implemented
                selectors:
                    _process: not_implemented
                    selector:
                        _process: not_implemented
                        config:
                            _process: not_implemented
                            facility:
                                _process: not_implemented
                            severity:
                                _process: not_implemented
                        facility:
                            _process: not_implemented
                        severity:
                            _process: not_implemented
                        state:
                            _process: not_implemented
                state:
                    _process: not_implemented
    memory:
        _process: not_implemented
        state:
            _process: not_implemented
    ntp:
        _process: not_implemented
        config:
            _process: not_implemented
            enable-ntp-auth:
                _process: not_implemented
            enabled:
                _process: not_implemented
            ntp-source-address:
                _process: not_implemented
        ntp-keys:
            _process: not_implemented
            ntp-key:
                _process: not_implemented
                config:
                    _process: not_implemented
                    key-id:
                        _process: not_implemented
                    key-type:
                        _process: not_implemented
                    key-value:
                        _process: not_implemented
                key-id:
                    _process: not_implemented
                state:
                    _process: not_implemented
        servers:
            _process: not_implemented
            server:
                _process: not_implemented
                address:
                    _process: not_implemented
                config:
                    _process: not_implemented
                    address:
                        _process: not_implemented
                    association-type:
                        _process:  not_implemented
                    iburst:
                        _process: not_implemented
                    port:
                        _process: not_implemented
                    prefer:
                        _process: not_implemented
                    version:
                        _process: not_implemented
                state:
                    _process: not_implemented
        state:
            _process: not_implemented
    processes:
        _process: not_implemented
        process:
            _process: not_implemented
    ssh-server:
        _process: not_implemented
        config:
            _process: not_implemented
            enable:
                _process: not_implemented
            protocol-version:
                _process: not_implemented
            rate-limit:
                _process: not_implemented
            session-limit:
                _process: not_implemented
            timeout:
                _process: not_implemented
        state:
            _process: not_implemented
    state:
        _process: not_implemented
    telnet-server:
        _process: not_implemented
        config:
            _process: not_implemented
            enable:
                _process: not_implemented
            rate-limit:
                _process: not_implemented
            session-limit:
                _process: not_implemented
            timeout:
                _process: not_implemented
        state:
            _process: not_implemented
