---
metadata:
    processor: TextTree

ipv4:
    _process: unnecessary
    config:
        _process: unnecessary
        enabled:
            _process:
                - path: "switchport"
                  present: no
        mtu:
            _process: not_implemented
    addresses:
        _process: unnecessary
        address:
            _process:
                - path: "ip.address.?prefix.?mask"
                  regexp: "^(?P<value>\\d+\\.\\d+\\.\\d+\\.\\d+)"
                  key: prefix
            ip:
                _process: unnecessary
            config:
                _process: unnecessary
                ip:
                    _process:
                        - path: prefix
                prefix-length:
                    _process:
                        - path: mask
                          post: "{{ value|netmask_to_cidr }}"
            vrrp:
                _process: not_implemented
                vrrp-group:
                    _process: not_implemented
                    virtual-router-id:
                        _process: not_implemented
                    config:
                        _process: not_implemented
                        virtual-address:
                            _process: not_implemented
                        priority:
                            _process: not_implemented
                        preempt:
                            _process: not_implemented
                        advertisement-interval:
                            _process: not_implemented
                        virtual-router-id:
                            _process: not_implemented
                        preempt-delay:
                            _process: not_implemented
                        accept-mode:
                            _process: not_implemented
    unnumbered:
        _process: not_implemented
        config:
            _process: not_implemented
            enabled:
                _process: not_implemented
        interface-ref:
            _process: not_implemented
            config:
                _process: not_implemented
                interface:
                    _process: not_implemented
                subinterface:
                    _process: not_implemented
    neighbors:
        _process: not_implemented
        neighbor:
            _process: not_implemented
            ip:
                _process: not_implemented
            config:
                _process: not_implemented
                ip:
                    _process: not_implemented
                link-layer-address:
                    _process: not_implemented
