---
metadata:
    processor: JSONParser
    execute:
        - method: _rpc
          kwargs:
            get: data/openconfig-interfaces:interfaces

interfaces:
    _process:
      - from: root_interfaces.0
        path: openconfig-interfaces:interfaces
    interface:
        _process: 
          - path: interface
            key: name
        config:
            _process: 
              - path: config
            description:
                _process:  
                  - path: description
            enabled:
                _process:  
                  - path: enabled
            mtu:
                _process:  
                  - path: mtu
            name:
                _process:  
                  - path: name
            type:
                _process:    
                  - path: type
                    regexp: ".*:(?P<value>[a-zA-Z]+)"
        hold-time:
            _process: not_implemented
            config:
                _process: not_implemented
                down:
                    _process: not_implemented
                up:
                    _process: not_implemented
            state:
                _process: unnecessary
        name:
            _process: unnecessary
        subinterfaces:
            _process: 
              - path: subinterfaces
            subinterface:
                _process: 
                  - path: subinterface
                    key: '{{ index }}'
                config:
                    _process: 
                      - path: config
                    description:
                        _process: 
                          - path: description
                    enabled:
                        _process:
                          - path: enabled
                    index:
                        _process: unnecessary
                    name:
                        _process:
                          - path: name
                index:
                    _process: unnecessary
